routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/clear', function() {
    Artisan::call('cache:clear');
    Artisan::call('config:clear');
    Artisan::call('route:clear');
    Artisan::call('view:clear');

    return "Cache is cleared";
});

Route::get( '/', 'HomeController@index' )->name('home');
Route::get( '/games/', 'Pages\GamesController@index' )->name('all_games');
Route::get( '/games/{slug}/', 'Pages\GamesController@showSingle' );

Route::get( '/news/', 'Pages\NewsController@index' )->name('all_news');
Route::get( '/news/{slug}/', 'Pages\NewsController@showSingle' );
Route::get( '/tag/{slug}', 'Pages\NewsController@tagSingle' )->name( 'tag.show' );
Route::get( '/category/{slug}', 'Pages\NewsController@categorySingle' )->name( 'category.show' );

Route::post( '/subscribe', 'SubController@subscribe' );
Route::get( '/verify/{token}', 'SubController@verify' );

Route::group(['middleware' => 'auth' ], function () {
    Route::get( '/profile', 'ProfileController@index' );
    Route::post( '/profile', 'ProfileController@store' );
    Route::get( '/logout', 'AuthController@logout' );
});

Route::group( ['middleware' => 'guest'], function () {
//    Route::get( '/register', 'AuthController@registerForm' );
//    Route::post( '/register', 'AuthController@register' );
    Route::get( '/login', 'AuthController@loginForm' )->name( 'login' );
    Route::post( '/login', 'AuthController@login' );
});

Route::group( ['prefix'=>'admin', 'namespace'=>'Admin', 'middleware' => 'admin'], function () {
    Route::get( '/', 'DashboardController@index' );
    Route::get( '/telegramAPI/{id}', 'includes\telegramAPI\TelegramController@index' )
        ->name('telegramAPI.send_request');
    Route::resource( '/categories', 'CategoriesController' );
    Route::resource( '/tags', 'TagsController' );
    Route::resource( '/pages', 'PagesController' );
    Route::resource( '/users', 'UsersController' );
    Route::resource( '/posts', 'PostsController' );
    Route::resource( '/posts-game', 'GamesController' );
    Route::resource( '/subscribers', 'SubscribersController' );
    Route::resource( '/settings', 'SettingsController' );
    Route::resource( '/vacancies', 'VacanciesController' );
});

/**
 * Ajax requests
 */
Route::post( '/admin/img/mcedit', 'Admin\includes\tinyMCE\MediaController@store' )->name( 'admin.mcedit' );
Route::post( '/News/ajaxPOST', 'Pages\NewsController@loadAjaxPosts' )->name( 'ajax.getFourPosts' );
Route::post( '/auth/cookies', 'CookiesController@index' )->name( 'ajax.setCookies' );

/**
 * Sitemaps
 */
Route::get('/sitemap', 'SitemapController@index');
Route::get('/sitemap/posts', 'SitemapController@posts');
Route::get('/sitemap/pages', 'SitemapController@pages');
Route::get('/sitemap/categories', 'SitemapController@categories');
Route::get('/sitemap/tags', 'SitemapController@tags');
Route::get('/sitemap/games', 'SitemapController@games');

/**
 * Static page
 */
Route::get('/privacy_policy', 'Pages\TechController@privacy_policy')->name('privacy_policy');
Route::get('/about_us/', 'Pages\AboutUsController@index')->name('about_us');
Route::get('/careers', 'Pages\CareersController@render_page')->name('careers');
Route::post( '/resume', 'Pages\CareersController@send_resume' )->name('send_resume');

resources/views/admin/_sidebar.blade.php
<!-- =============================================== -->

<!-- Left side column. contains the sidebar -->
<aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
        <!-- Sidebar user panel -->
{{--        <div class="user-panel">--}}
{{--            <div class="pull-left image">--}}
{{--                <img src="/img/user2-160x160.jpg" class="img-circle" alt="User Image">--}}
{{--            </div>--}}
{{--            <div class="pull-left info">--}}
{{--                <p>Denys Polkovnyk</p>--}}
{{--            </div>--}}
{{--        </div>--}}
        <!-- search form -->
        <form action="#" method="get" class="sidebar-form">
            <div class="input-group">
                <input type="text" name="q" class="form-control" placeholder="Search...">
                <span class="input-group-btn">
                <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i>
                </button>
              </span>
            </div>
        </form>
        <!-- /.search form -->
        <!-- sidebar menu: : style can be found in sidebar.less -->
        <ul class="sidebar-menu">
            <li class="header">Навигация</li>
            <li class="treeview">
                <a href="/admin/">
                    <i class="fa fa-dashboard"></i> <span>Админ панель</span>
                </a>
            </li>
            <li>
                <a href="{{route('pages.index')}}">
                    <i class="fa fa-book"></i>
                    <span>Страницы</span>
                </a>
            </li>
            <li>
                <a href="{{route('posts.index')}}">
                    <i class="fa fa-sticky-note-o"></i>
                    <span>Посты</span>
                </a>
            </li>
            <li>
                <a href="{{route('categories.index')}}">
                    <i class="fa fa-list-ul"></i>
                    <span>Категории</span>
                </a>
            </li>
            <li>
                <a href="{{route('tags.index')}}">
                    <i class="fa fa-tags"></i>
                    <span>Теги</span>
                </a>
            </li>
            <li>
                <a href="{{route('posts-game.index')}}">
                    <i class="fa fa-futbol-o"></i>
                    <span>Игры</span>
                </a>
            </li>
            <li>
                <a href="{{route('users.index')}}">
                    <i class="fa fa-users"></i>
                    <span>Пользователи</span>
                </a>
            </li>
            <li>
                <a href="{{route('subscribers.index')}}">
                    <i class="fa fa-user-plus"></i>
                    <span>Подписчики</span>
                </a>
            </li>
            <li>
                <a href="{{route('vacancies.index')}}">
                    <i class="fa ion-social-linkedin"></i>
                    <span>Вакансии</span>
                </a>
            </li>
            <li>
                <a href="#">
                    <i class="fa fa-pie-chart"></i>
                    <span>Статистика</span>
                </a>
            </li>
            <li>
                <a href="#">
                    <i class="fa fa-street-view"></i>
                    <span>Письма</span>
                </a>
            </li>
            <li>
                <a href="{{route('settings.index')}}">
                    <i class="fa fa fa-sliders"></i>
                    <span>Настройки</span>
                </a>
            </li>
        </ul>
    </section>
    <!-- /.sidebar -->
</aside>

<!-- =============================================== -->

resources/views/admin/dashboard.blade.php
@extends('admin.layout')

@section('content')
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Добро пожаловать
            <small>{{Auth::user()->name}}</small>
        </h1>
    </section>

    <!-- Main content -->
    <section class="content">
        <!-- Default box -->
        <div class="box">
            <div class="box-header with-border">
                <h3 class="box-title">Главная страница</h3>
            </div>
            <div class="box-body">
                <p>В Админ-панели есть администрация и редактора, которые занимаются заполнением сайта
                из данной панели.</p>
                <br>Если вы наблюдаете или возникают какие-то проблемы с работой Админ-панели,</br>
                то пожалуйста предоставьте главному админу скриншоты и ссылку, где обнаружили проблему.</p>
                <p>Сайт и Админ-панель находится в постоянной разработке.</p>
            </div>
            <!-- /.box-body -->
            <div class="box-footer">
                <p>Контактная информация администратора:</p>
                <ul>
                    <li>E-mail: <a href="mailTo:polkovnik_denis@live.com">polkovnik_denis@live.com</a></li>
                    <li>Telegram: @polkovnik_denis</li>
                    <li>Discord: <a href="https://discord.gg/rzdX9bsQ">HiMeli Server</a></li>
                </ul>
            </div>
            <!-- /.box-footer-->
        </div>

        <div class="container">
            <div class="row">

            </div>
        </div>
        <!-- /.box -->

    </section>
    <!-- /.content -->
</div>
@endsection

resources/views/admin/errors.blade.php
@if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

resources/views/admin/layout.blade.php
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>HiMeli | Admin Panel</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <script src="https://cdn.tiny.cloud/1/cc96leyouwqirwu4jpi3qcp3iigcnpx8zye70b69oobfnhg0/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>

    <link rel="stylesheet" href="/css/admin.css">
    <style>
        table.table form{
            display: inline-block;
        }
        button.delete{
            background: transparent;
            border: none;
            color: #337ab7;
            padding: 0px;
        }
    </style>
</head>
<body class="hold-transition skin-blue sidebar-mini">
<!-- Site wrapper -->
<div class="wrapper">

    <header class="main-header">
        <!-- Logo -->
        <a href="/" class="logo">
            <!-- mini logo for sidebar mini 50x50 pixels -->
            <span class="logo-mini"><b>Hi</b></span>
            <!-- logo for regular state and mobile devices -->
            <span class="logo-lg"><b>Admin</b>Panel</span>
        </a>
        <!-- Header Navbar: style can be found in header.less -->
        <nav class="navbar navbar-static-top">
            <!-- Sidebar toggle button-->
            <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>

            <div class="navbar-custom-menu">
                <ul class="nav navbar-nav">
{{--                    <!-- Messages: style can be found in dropdown.less-->--}}
{{--                    <li class="dropdown messages-menu">--}}
{{--                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">--}}
{{--                            <i class="fa fa-envelope-o"></i>--}}
{{--                            <span class="label label-success">4</span>--}}
{{--                        </a>--}}
{{--                        <ul class="dropdown-menu">--}}
{{--                            <li class="header">You have 4 messages</li>--}}
{{--                            <li>--}}
{{--                                <!-- inner menu: contains the actual data -->--}}
{{--                                <ul class="menu">--}}
{{--                                    <li><!-- start message -->--}}
{{--                                        <a href="#">--}}
{{--                                            <div class="pull-left">--}}
{{--                                                <img src="/public/img/user2-160x160.jpg" class="img-circle" alt="User Image">--}}
{{--                                            </div>--}}
{{--                                            <h4>--}}
{{--                                                Support Team--}}
{{--                                                <small><i class="fa fa-clock-o"></i> 5 mins</small>--}}
{{--                                            </h4>--}}
{{--                                            <p>Why not buy a new awesome theme?</p>--}}
{{--                                        </a>--}}
{{--                                    </li>--}}
{{--                                    <!-- end message -->--}}
{{--                                </ul>--}}
{{--                            </li>--}}
{{--                            <li class="footer"><a href="#">See All Messages</a></li>--}}
{{--                        </ul>--}}
{{--                    </li>--}}
{{--                    <!-- Notifications: style can be found in dropdown.less -->--}}
{{--                    <li class="dropdown notifications-menu">--}}
{{--                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">--}}
{{--                            <i class="fa fa-bell-o"></i>--}}
{{--                            <span class="label label-warning">10</span>--}}
{{--                        </a>--}}
{{--                        <ul class="dropdown-menu">--}}
{{--                            <li class="header">You have 10 notifications</li>--}}
{{--                            <li>--}}
{{--                                <!-- inner menu: contains the actual data -->--}}
{{--                                <ul class="menu">--}}
{{--                                    <li>--}}
{{--                                        <a href="#">--}}
{{--                                            <i class="fa fa-users text-aqua"></i> 5 new members joined today--}}
{{--                                        </a>--}}
{{--                                    </li>--}}
{{--                                </ul>--}}
{{--                            </li>--}}
{{--                            <li class="footer"><a href="#">View all</a></li>--}}
{{--                        </ul>--}}
{{--                    </li>--}}
{{--                    <!-- Tasks: style can be found in dropdown.less -->--}}
{{--                    <li class="dropdown tasks-menu">--}}
{{--                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">--}}
{{--                            <i class="fa fa-flag-o"></i>--}}
{{--                            <span class="label label-danger">9</span>--}}
{{--                        </a>--}}
{{--                        <ul class="dropdown-menu">--}}
{{--                            <li class="header">You have 9 tasks</li>--}}
{{--                            <li>--}}
{{--                                <!-- inner menu: contains the actual data -->--}}
{{--                                <ul class="menu">--}}
{{--                                    <li><!-- Task item -->--}}
{{--                                        <a href="#">--}}
{{--                                            <h3>--}}
{{--                                                Design some buttons--}}
{{--                                                <small class="pull-right">20%</small>--}}
{{--                                            </h3>--}}
{{--                                            <div class="progress xs">--}}
{{--                                                <div class="progress-bar progress-bar-aqua" style="width: 20%" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">--}}
{{--                                                    <span class="sr-only">20% Complete</span>--}}
{{--                                                </div>--}}
{{--                                            </div>--}}
{{--                                        </a>--}}
{{--                                    </li>--}}
{{--                                    <!-- end task item -->--}}
{{--                                </ul>--}}
{{--                            </li>--}}
{{--                            <li class="footer">--}}
{{--                                <a href="#">View all tasks</a>--}}
{{--                            </li>--}}
{{--                        </ul>--}}
{{--                    </li>--}}
{{--                    <!-- User Account: style can be found in dropdown.less -->--}}
                    <li class="dropdown user user-menu">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <img src="{{Auth::user()->getAvatar()}}" class="user-image" alt="User Image">
                            <span class="hidden-xs">{{Auth::user()->name}}</span>
                        </a>
                        <ul class="dropdown-menu">
                            <!-- User image -->
                            <li class="user-header">
                                <img src="{{Auth::user()->getAvatar()}}" class="img-circle" alt="User Image">
                                <p>{{Auth::user()->name}} - HiMeli(Admin)</p>
                            </li>
{{--                            <!-- Menu Body -->--}}
{{--                            <li class="user-body">--}}
{{--                                <div class="row">--}}
{{--                                    <div class="col-xs-4 text-center">--}}
{{--                                        <a href="#">Followers</a>--}}
{{--                                    </div>--}}
{{--                                    <div class="col-xs-4 text-center">--}}
{{--                                        <a href="#">Sales</a>--}}
{{--                                    </div>--}}
{{--                                    <div class="col-xs-4 text-center">--}}
{{--                                        <a href="#">Friends</a>--}}
{{--                                    </div>--}}
{{--                                </div>--}}
{{--                                <!-- /.row -->--}}
{{--                            </li>--}}
                            <!-- Menu Footer-->
                            <li class="user-footer">
                                <div class="pull-left">
                                    <a href="/profile/" class="btn btn-default btn-flat">Profile</a>
                                </div>
                                <div class="pull-right">
                                    <a href="/logout/" class="btn btn-default btn-flat">Sign out</a>
                                </div>
                            </li>
                        </ul>
                    </li>
                    <!-- Control Sidebar Toggle Button -->
{{--                    <li>--}}
{{--                        <a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>--}}
{{--                    </li>--}}
                </ul>
            </div>
        </nav>
    </header>

    @include('admin._sidebar')

    <!-- Content Wrapper. Contains page content -->

    @yield('content')
    <!-- /.content-wrapper -->

    <footer class="main-footer">
        <div class="pull-right hidden-xs">
            <b>Version</b> 2.21.10.1
        </div>
        <strong>Copyright &copy; 2021 <a href="https://himeli.org/">HiMeli</a>.</strong> All rights reserved.
    </footer>

    <!-- /.control-sidebar -->
    <!-- Add the sidebar's background. This div must be placed
         immediately after the control sidebar -->
    <div class="control-sidebar-bg"></div>
</div>
<!-- ./wrapper -->

<script src="/js/admin.js"></script>

</body>
</html>

resources/views/admin/settings.blade.php
@extends('admin.layout')

@section('content')
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">

        @if (session('status'))
            <div class="alert alert-success">
                {{session('status')}}
            </div>
        @endif

        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>Основные настройки сайта</h1>
        </section>

        <!-- Main content -->
        <section class="content">
        {{Form::open(['route' => 'settings.store', 'files'	=>	true])}}
        <!-- Default box -->
            @include('admin.errors')

            <div class="box">
                <div class="box-header with-border">
                    <ul class="tabs-list">
                        <li class="tab-bar-item general active">
                            <a data-tab="general" href="javascript:void(0);">Основные настройки</a>
                        </li>
                        <li class="tab-bar-item smtp">
                            <a data-tab="smtp" href="javascript:void(0);">Настройки SMTP</a>
                        </li>
                        <li class="tab-bar-item seo">
                            <a data-tab="seo" href="javascript:void(0);">Настройки SEO</a>
                        </li>
                        <li class="tab-bar-item widgets">
                            <a data-tab="widgets" href="javascript:void(0);">Виджеты и роли</a>
                        </li>
                        <li class="tab-bar-item posts">
                            <a data-tab="posts" href="javascript:void(0);">Выводы постов</a>
                        </li>
                    </ul>
                </div>
                <div class="box-body tabs-body">
                    <div id="general" class="tab-item active">
                        <div class="col-md-3">
                            <div class="form-group">
                                <label for="site_name">Название сайта</label>
                                <input type="text" name="options_name[site_name]" class="form-control" id="site_name" placeholder="" value="@isset($options[0]) {{$options[0]->options_value}} @endisset">
                            </div>
                            <div class="form-group">
                                <label for="site_description">Описание сайта</label>
                                <input type="text" name="options_name[site_description]" class="form-control" id="site_description" placeholder="" value="@isset($options[1]) {{$options[1]->options_value}} @endisset">
                            </div>
                        </div>
                    </div>
                    <div id="smtp" class="tab-item">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="site_smtp_host">Почтовый сервер(хост)</label>
                                <input type="text" name="options_name[site_smtp_host]" class="form-control" id="site_smtp_host" placeholder="" value="@isset($options[2]) {{$options[2]->options_value}} @endisset">
                            </div>
                            <div class="form-group">
                                <label for="site_smtp_port">Порт сервера</label>
                                <input type="text" name="options_name[site_smtp_port]" class="form-control" id="site_smtp_port" placeholder="" value="@isset($options[3]) {{$options[3]->options_value}} @endisset">
                            </div>
                            <div class="form-group">
                                <label for="site_smtp_user_name">Имя пользователя(E-mail)</label>
                                <input type="text" name="options_name[site_smtp_user_name]" class="form-control" id="site_smtp_user_name" placeholder="" value="@isset($options[4]) {{$options[4]->options_value}} @endisset">
                            </div>
                            <div class="form-group">
                                <label for="site_smtp_user_password">Пароль пользователя</label>
                                <input type="password" name="options_name[site_smtp_user_password]" class="form-control" id="site_smtp_user_password" placeholder="" value="@isset($options[5]) {{$options[5]->options_value}} @endisset">
                            </div>
                        </div>
                    </div>
                    <div id="seo" class="tab-item">
                        <div class="col-md-3">
                            <div class="form-group">
                                <label for="site_seo_pictures_default">Изображение для соц.сетей (по умолчанию)</label>
                                <input type="file" name="options_name[site_seo_pictures_default]" id="site_seo_pictures_default" value="@isset($options[6]) {{$options[6]->options_value}} @endisset">
                            </div>
                        </div>
                    </div>
                    <div id="widgets" class="tab-item">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="widgets_options">Вывод виджетов на главную админ панели</label>
                            </div>
                        </div>
                    </div>
                    <div id="posts" class="tab-item">
                        <div class="col-md-3">
                            <div class="form-group">
                                <label for="posts_options">Вывод постов</label>
{{--                                <input type="number" name="options_name[posts_options]" class="form-control" id="posts_options" placeholder="">--}}
                            </div>
                        </div>
                    </div>
                </div>

                <!-- /.box-body -->
                <div class="box-footer">
                    <button class="btn btn-success pull-right">Добавить</button>
                </div>
                <!-- /.box-footer-->
            </div>
            <!-- /.box -->
            {{Form::close()}}
        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
@endsection