routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/clear', function() {
    Artisan::call('cache:clear');
    Artisan::call('config:clear');
    Artisan::call('route:clear');
    Artisan::call('view:clear');

    return "Cache is cleared";
});

Route::get( '/', 'HomeController@index' )->name('home');
Route::get( '/games/', 'Pages\GamesController@index' )->name('all_games');
Route::get( '/games/{slug}/', 'Pages\GamesController@showSingle' );

Route::get( '/news/', 'Pages\NewsController@index' )->name('all_news');
Route::get( '/news/{slug}/', 'Pages\NewsController@showSingle' );
Route::get( '/tag/{slug}', 'Pages\NewsController@tagSingle' )->name( 'tag.show' );
Route::get( '/category/{slug}', 'Pages\NewsController@categorySingle' )->name( 'category.show' );

Route::post( '/subscribe', 'SubController@subscribe' );
Route::get( '/verify/{token}', 'SubController@verify' );

Route::group(['middleware' => 'auth' ], function () {
    Route::get( '/profile', 'ProfileController@index' );
    Route::post( '/profile', 'ProfileController@store' );
    Route::get( '/logout', 'AuthController@logout' );
});

Route::group( ['middleware' => 'guest'], function () {
//    Route::get( '/register', 'AuthController@registerForm' );
//    Route::post( '/register', 'AuthController@register' );
    Route::get( '/login', 'AuthController@loginForm' )->name( 'login' );
    Route::post( '/login', 'AuthController@login' );
});

Route::group( ['prefix'=>'admin', 'namespace'=>'Admin', 'middleware' => 'admin'], function () {
    Route::get( '/', 'DashboardController@index' );
    Route::get( '/telegramAPI/{id}', 'includes\telegramAPI\TelegramController@index' )
        ->name('telegramAPI.send_request');
    Route::resource( '/categories', 'CategoriesController' );
    Route::resource( '/tags', 'TagsController' );
    Route::resource( '/pages', 'PagesController' );
    Route::resource( '/users', 'UsersController' );
    Route::resource( '/posts', 'PostsController' );
    Route::resource( '/posts-game', 'GamesController' );
    Route::resource( '/subscribers', 'SubscribersController' );
    Route::resource( '/settings', 'SettingsController' );
    Route::resource( '/vacancies', 'VacanciesController' );
});

/**
 * Ajax requests
 */
Route::post( '/admin/img/mcedit', 'Admin\includes\tinyMCE\MediaController@store' )->name( 'admin.mcedit' );
Route::post( '/News/ajaxPOST', 'Pages\NewsController@loadAjaxPosts' )->name( 'ajax.getFourPosts' );
Route::post( '/auth/cookies', 'CookiesController@index' )->name( 'ajax.setCookies' );

/**
 * Sitemaps
 */
Route::get('/sitemap', 'SitemapController@index');
Route::get('/sitemap/posts', 'SitemapController@posts');
Route::get('/sitemap/pages', 'SitemapController@pages');
Route::get('/sitemap/categories', 'SitemapController@categories');
Route::get('/sitemap/tags', 'SitemapController@tags');
Route::get('/sitemap/games', 'SitemapController@games');

/**
 * Static page
 */
Route::get('/privacy_policy', 'Pages\TechController@privacy_policy')->name('privacy_policy');
Route::get('/about_us/', 'Pages\AboutUsController@index')->name('about_us');
Route::get('/careers', 'Pages\CareersController@render_page')->name('careers');
Route::post( '/resume', 'Pages\CareersController@send_resume' )->name('send_resume');

app/Http/Controllers/SubController.php
<?php

namespace App\Http\Controllers;

use App\Mail\SubscribeEmail;
use App\Subscription;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Mail;

class SubController extends Controller
{
    public function subscribe(Request $request)
    {
        $this->validate($request, [
            'email' => 'required|email|unique:subscriptions'
        ]);

        $subs = Subscription::add($request->get('email'));
        $subs->generateToken();

        Mail::to($subs)->send(new SubscribeEmail($subs));

        return redirect()->back()->with('status', 'Checked your Email!');
    }

    public function verify($token)
    {
        $subs = Subscription::where('token', $token)->firstOrFail();
        $subs->token = null;
        $subs->save();

        return redirect('/news/')->with('status', 'Your mail is confirmed');
    }
}

resources/views/admin/subs/create.blade.php
@extends('admin.layout')

@section('content')

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->

        <!-- Main content -->
        <section class="content">
        {{Form::open(['route'	=>	'subscribers.store'])}}
        <!-- Default box -->
            <div class="box">
                <div class="box-header with-border">
                    <h3 class="box-title">Добавляем подписчика</h3>
                    @include('admin.errors')
                </div>
                <div class="box-body">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="exampleInputEmail1">Email</label>
                            <input type="text" class="form-control" id="exampleInputEmail1" placeholder="" name="email" value="{{old('email')}}">
                        </div>
                    </div>
                </div>
                <!-- /.box-body -->
                <div class="box-footer">
                    <button class="btn btn-success pull-right">Добавить</button>
                </div>
                <!-- /.box-footer-->
            </div>
            <!-- /.box -->
            {{Form::close()}}
        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
@endsection

resources/views/admin/subs/index.blade.php
@extends('admin.layout')

@section('content')
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <ol class="breadcrumb">
                <li><a href="/admin/"><i class="fa fa-dashboard"></i> Админ-панель</a></li>
                <li class="active">Подписчики</li>
            </ol>
        </section>

        <!-- Main content -->
        <section class="content">

            <!-- Default box -->
            <div class="box">
                <div class="box-header">
                    <h3 class="box-title">Список подписчиков</h3>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <div class="form-group">
                        <a href="{{route('subscribers.create')}}" class="btn btn-success">Добавить</a>
                    </div>
                    <table id="example1" class="table table-bordered table-striped">
                        <thead>
                        <tr>
                            <th>ID</th>
                            <th>Email</th>
                            <th>Действия</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($subs as $subscriber)
                            <tr>
                                <td>{{$subscriber->id}}</td>
                                <td>{{$subscriber->email}}
                                </td>
                                <td>
                                    {{Form::open(['route'=>['subscribers.destroy', $subscriber->id], 'method'=>'delete'])}}
                                    <button onclick="return confirm('are you sure?')" type="submit" class="delete">
                                        <i class="fa fa-remove"></i>
                                    </button>

                                    {{Form::close()}}
                                </td>
                            </tr>
                        @endforeach
                        </tfoot>
                    </table>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
@endsection